### ISSUE TITLE
Empty Voice2.package file in Base.v11

### ISSUE THREAD

**Issue by spockthewok** [mintalien/The-Puppets-2-Definitive-Edition#1]
I noticed my sims' voices were missing during some interactions, such as talking on the phone. This was due to the fact that the Voice2.package file (located in Double Deluxe\Base\TSData\Res\Sound) included in v11 is empty - the same file in v10 is almost 100MB. Replacing the file with the one from v10 fixed the issue.

**Comment by mintalien** [comment]
Thank you very much for pointing this out @spockthewok, I have fixed the corrupted file in the upcoming release!
